#==============================================================================#
#                                 ALACRITTY                                    #
#                                                                              #
# @file:   $HOME/.confg/alacritty/alacritty.yml                                #
# @author: hradecek <ivohradek@gmail.com>                                      #
#==============================================================================#
import = [
  "~/.config/alacritty/colors.toml"
]

[env]
TERM = "alacritty"
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"

[window]
title = "Terminal"

[font]
size = 12

[font.normal]
family = "mononoki nerd font"
style = "Regular"

