[colors.primary]
background = '#00141a'
foreground = '#839495'

[colors.normal]
black = '#00141a'
red = '#dc312e'
green = '#859900'
yellow = '#b38600'
blue = '#278bd3'
magenta = '#d33682'
cyan = '#2aa298'
white = '#ede7d4'

[colors.bright]
black = '#002d38'
red = '#f65351'
green = '#b7fa00'
yellow = '#ffbf00'
blue = '#47adf5'
magenta = '#f254a1'
cyan = '#2beede'
white = '#fdf6e2'

[colors.selection]
background = "0x2d4f67"
foreground = "0xc8c093"

[[colors.indexed_colors]]
index = 16
color = "0xffa066"

[[colors.indexed_colors]]
index = 17
color = "0xff5d62"
