#==============================================================================#
#                                   FUZZEL                                     #
#                                                                              #
# @file:   $HOME/.config/fuzzel/fuzzel.ini                                     #
# @author: hradecek <ivohradek@gmail.com>                                      #
#==============================================================================#

[main]
font=mononoki nerd font:size=12
terminal=alacritty -e
layer=overlay
width=40
horizontal-pad=20
vertical-pad=10
inner-pad=10
lines=15

[colors]
background=0f0f0fdd
text=f0f0f0ff
prompt=56c92bff
input=f0f0f0ff
match=56c92bff
selection=337418ff
selection-text=f0f0f0ff
selection-match=6fe03dff
border=44a022ff

[border]
width=2
radius=0

