#==============================================================================#
#                                   FUZZEL                                     #
#                                                                              #
# @file:   $HOME/.config/fuzzel/fuzzel.ini                                     #
# @author: hradecek <ivohradek@gmail.com>                                      #
#==============================================================================#

[main]
font=mononoki nerd font:size=12
terminal=alacritty -e
layer=overlay
width=40
horizontal-pad=20
vertical-pad=10
inner-pad=10
lines=15

[colors]
background=0d1410dd
text=d6e8dcff
prompt=5fa876ff
input=d6e8dcff
match=5fa876ff
selection=2a3a30ff
selection-text=d6e8dcff
selection-match=8fe0a8ff
border=5fa876ff

[border]
width=2
radius=6

