#!/bin/sh
#=============================================================================#
# File:   ~/.bashrc                                                           #
# Author: hradecek <ivohradek@gmail.com>                                      #
#=============================================================================#

# Directory where everything is stored
BASH="$HOME/dotfiles/bash"

# Choose theme
THEME="hradecek"

# History control
HISTSIZE=2000
HISFILESIZE=10000
HISTCONTROL=ignoreboth

# Press CTRL+D two time to exit shell
IGNOREEOF="1"

# sudo, man completition
complete -cf man
complete -cf sudo

# Auto cd
shopt -s autocd

# Combine multiline commands into one in history
shopt -s cmdhist

# Include .files when globbing
shopt -s dotglob

# Glob expands rather empty
shopt -s nullglob

# Append to history
shopt -s histappend

# Autocorrect typos in `cd`
shopt -s cdspell

# Disable old XON/XOFF flow control
stty -ixon

# Dir colors
eval "$(dircolors ~/.dircolors)"

# Environment variables
export EDITOR="/usr/bin/vim"
export GOPATH="$HOME/go"
export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")
export ANDROID_HOME="/opt/android-sdk"
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

# Add user bin
[[ -d $HOME/bin ]] && PATH="$PATH:$HOME/bin"

# Add go
[[ -d $GOPATH ]] && PATH="$PATH:$GOPATH/bin"

# Add ruby
[[ $(which ruby) ]] && PATH="$PATH:$HOME/.gem/ruby/2.2.0/bin"

# Add Android SDK
[[ -d /opt/android-sdk ]] && PATH="$PATH:/opt/android-sdk/platform-tools/:/opt/android-sdk/tools"

# Add 'cabal'
[[ -d $HOME/.cabal/bin ]] && PATH="$HOME/.cabal/bin:$PATH"

# Load 'mysql-colorize'
[[ -d $BASH/plugins/mysql-colorize ]] && source "$BASH/plugins/mysql-colorize/mysql-colorize.bash"

# Load qfc
[[ -s "$HOME/.qfc/bin/qfc.sh" ]] && source "$HOME/.qfc/bin/qfc.sh"

# Alias 'thefuck' to 'fuck'
[[ $(which thefuck) ]] && eval "$(thefuck --alias)"

# Configure 'hstr'
if [[ $(which hstr) ]]; then
    export HH_CONFIG=hicolor
    export PROMPT_COMMAND="history -a; history -n; ${PROMPT_COMMAND}"
    [[ $- =~ .*i.* ]] && bind '"\C-r": "\C-a hh \C-j"'

fi

# Load extension functions
FUNCTIONS="$BASH/functions.bash"
[[ -f $FUNCTIONS ]] && source $FUNCTIONS

# Load completions and aliases
ALIASES="$BASH/aliases/*.aliases.bash"
COMPLETIONS="$BASH/completions/*.completion.bash"
for file in $COMPLETIONS $ALIASES; do
    [[ -f $file ]] && source $file
done

#Load theme
source "$BASH/themes/colors.theme.bash"
source "$BASH/themes/base.theme.bash"
source "$BASH/themes/$THEME/${THEME}.theme.bash"

# Main prompt
if [ $PROMPT ]; then
    export PS1=$PROMPT
fi

fortune | cowsay -f tux | lolcat
